name: bootcamp104 backend deployment

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/backendDeploy.yml'

env:
  GITHUB_USER: ishtiaqsamdani007

jobs:
  deploy_template:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        service: [action-service,api-gateway,candidates-service,cloud-config-server,reports-services,searches-services,service-registry,user-service]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto' 
          java-version: '11'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ env.GITHUB_USER }}
          password: ${{ secrets.CR_PAT }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EKS_CLUSTER_REGION }}

      - name: Adding EKS cluster and Build and Deploy the service
        env: 
          aws_region: ${{ secrets.EKS_CLUSTER_REGION }}
          cluster_name: ${{ secrets.EKS_CLUSTER_NAME}}
          SERVICE_NAME: ${{ matrix.service }}
        run: |
          aws eks --region $aws_region update-kubeconfig --name $cluster_name
          cd backend/${SERVICE_NAME}
          mvn clean package -DskipTests
          docker build -t ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:v${{ github.run_number }} .
          docker tag ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:v${{ github.run_number }} ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:latest
          docker push ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:v${{ github.run_number }}
          docker push ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:latest
          kubectl set image deployment/${SERVICE_NAME} ${SERVICE_NAME}-container=ghcr.io/${{ env.GITHUB_USER }}/bc-104-backend-${SERVICE_NAME}:v${{ github.run_number }}



          