
name: BOOTCAMP104 - frontend deployment

on:
  push:
    branches: 
      - "deployment"
    paths:
      - '.github/workflows/frontend-deployment.yml'
      - 'frontend/**'
      - '!frontend/db.json'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --legacy-peer-deps
    - run: npm run build --if-present

    -
      name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ secrets.USERNAME_GITHUB }}
        password: ${{ secrets.TOKEN_GITHUB }}
    -
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: frontend
        push: true
        tags: ghcr.io/miryalavenkat/frontend-104:v${{github.run_number}}

    -
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.EKS_CLUSTER_REGION }}

    - 
      name: Configure the EKS Cluster
      run: aws eks update-kubeconfig --region ${{ secrets.EKS_CLUSTER_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME}}
    -
      run: kubectl set image deployment react-app react-app=ghcr.io/miryalavenkat/frontend-104:v${{github.run_number}}

    