name: BOOTCAMP104 - Mockserver deployment 
run-name: Mockserver deployment update triggered by ${{ github.actor }}.
on:
  push:
    branches:
      - "deployment"
    paths:
      - ".github/workflows/mockserver-deployment.yml"
      - "frontend/db.json"
jobs:
  mockserver-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: deployment
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push the Image to GHCR
        run: |
          docker build . -t ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp104-mockserver:${{ github.sha }} -f mockserver.Dockerfile;
          docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp104-mockserver:${{ github.sha }}
     
  mockserver-deployment:
    needs: mockserver-build
    runs-on: ubuntu-latest
    steps:
      - name: Perform checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: deployment

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.EKS_CLUSTER_REGION }}

      - name: Configure the EKS Cluster
        run: aws eks update-kubeconfig --region ${{ secrets.EKS_CLUSTER_REGION }} --name ${{ secrets.EKS_CLUSTER_NAME }}

      - name: Update the deployment with latest image.
        run: kubectl set image deployment/mock-server-deployment mock-server-container=ghcr.io/${{ secrets.GHCR_USERNAME }}/bootcamp104-mockserver:${{ github.sha }}

      - name: Delete the Credentials
        run: rm -rf .aws .kube
