server:
  port: 9297

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Pranjal-mukherjee/config-server
          clone-on-start: true
