# deployment for spring boot microservice cloud-config-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: cloud-config-server
      project: bootcamp104
  template:
    metadata:
      labels:
        app: cloud-config-server
        project: bootcamp104
    spec:
      containers:
        - name: cloud-config-server-container
          image: ghcr.io/ishtiaqsamdani007/bc-104-backend-cloud-config-server
          imagePullPolicy: Always
          ports:
            - containerPort: 9297       
          env:
            # - name: EUREKA_INSTANCE_HOSTNAME
            #   value: cloud-config-server

            # - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            #   value: https://bc104-be.fe-assignment.tk/eureka/

            # - name: SPRING_DATASOURCE_URL
            #   value: jdbc:mysql://52.14.178.214:32301/chekr
      
            # - name: SPRING_DATASOURCE_PASSWORD
            #   value: password

            - name: SPRING_CLOUD_CONFIG_SERVER_GIT_URI
              value: https://github.com/Pranjal-mukherjee/deployment-config-server/
              
            # - name: SPRING_FLYWAY_ENABLED
            #   value: "false"
      
      imagePullSecrets:
        - name: my-docker-secret